# Generated by Django 3.1.2 on 2020-11-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instaladores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=25, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=25, unique=True, verbose_name='R.G.')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('tel01', models.CharField(max_length=9, verbose_name='Celular')),
                ('tel02', models.CharField(blank=True, max_length=9, null=True, verbose_name='Residencial')),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endereco.endereco')),
            ],
            options={
                'db_table': 'instaladores',
            },
        ),
    ]
