# Generated by Django 3.1.2 on 2020-11-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instaladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_created=True)),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Associado')),
                ('vendedor', models.CharField(max_length=30, unique=True, verbose_name='Vendedor')),
                ('obs', models.TextField(blank=True, max_length=300, null=True)),
                ('instalador', models.ForeignKey(default='Não especificado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instaladores.instaladores')),
            ],
        ),
    ]
