# Generated by Django 3.1.2 on 2020-11-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instalacao',
            table='instalacao',
        ),
    ]
