# Generated by Django 3.1.2 on 2020-11-30 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacao', '0003_instalacao_instalado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instalacao',
            options={'ordering': ['-data_pedido']},
        ),
        migrations.AddField(
            model_name='instalacao',
            name='endereco',
            field=models.CharField(default=1, max_length=60, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instalacao',
            name='tel01',
            field=models.CharField(default=1, max_length=60, verbose_name='Cellular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instalacao',
            name='tel02',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Residencial'),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='vistoria',
            field=models.CharField(choices=[('NÃO', 'NÃO'), ('SIM', 'SIM')], default='NÃO', max_length=3, null=True, verbose_name='Vistoria'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='data_pedido',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Associado'),
        ),
    ]
