# Generated by Django 3.1.2 on 2020-11-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacao', '0003_instalacao_instalado'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='endereco',
            field=models.CharField(default=1, max_length=60, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instalacao',
            name='vistoria',
            field=models.CharField(choices=[('NÃO', 'NÃO'), ('SIM', 'SIM')], default='NÃO', max_length=3, null=True, verbose_name='Vistoria'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Associado'),
        ),
    ]
