# Generated by Django 3.1.2 on 2020-11-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacao', '0004_auto_20201125_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='foto',
            field=models.FileField(default=1, upload_to='media/%y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instalacao',
            name='tel01',
            field=models.CharField(default=1, max_length=60, verbose_name='Cellular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instalacao',
            name='tel02',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Residencial'),
        ),
    ]
