# Generated by Django 3.1.2 on 2020-11-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacao', '0005_auto_20201127_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='media/%y/%m/%d/'),
        ),
    ]
