# Generated by Django 3.1.2 on 2020-11-30 20:48

from django.db import migrations, models
import django.db.models.deletion
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instalacao', '0004_auto_20201130_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('fotos', models.FileField(blank=True, null=True, upload_to=image.models.get_file_path)),
                ('instalacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instalacao.instalacao')),
            ],
        ),
    ]
