# Generated by Django 3.1.2 on 2020-11-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='veiculo',
        ),
    ]
