# Generated by Django 3.1.2 on 2020-11-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastreador',
            name='emei',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rastreador',
            name='nr_linha',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='rastreador',
            name='provedor',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
