# Generated by Django 3.1.2 on 2020-11-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_veiculo'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='clientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
    ]
